name: Benedicte Raae
favicon: null
layout_spectrum: 1
typography_spectrum: 0.56763
title: Benedicte Raae
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff4000'
    - '#ffffff'
    - '#ff875f'
    - '#ff0000'
    - '#ffb79f'
  brandStrength: 0.4679505580570549
  lightness: 0.875
  saturation: 0.5625
  rhythmicContrast: 0
purpose: []
